import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, Eye, HeartHandshake, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, SiteLayout } from "@/components/site/site-shell";

export const Route = createFileRoute("/about")({ head: () => ({
  meta: [
    { title: "عن مسور المتطورة | شريك تقني للأعمال السعودية" }, { name: "description", content: "تعرف على مسور المتطورة، شركة تقنية سعودية تبني مواقع ومنصات وأنظمة وحلول ذكاء اصطناعي بمنهج واضح وشراكة مستمرة." },
    { property: "og:title", content: "عن مسور المتطورة | شريكك التقني" }, { property: "og:description", content: "نحوّل تحديات الأعمال إلى منتجات رقمية موثوقة وفرص نمو قابلة للقياس." }, { property: "og:type", content: "website" }, { property: "og:url", content: "https://meswar.com/about" }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: "عن مسور المتطورة | شريكك التقني" }, { name: "twitter:description", content: "شركة تقنية سعودية تجمع فهم الأعمال بالتنفيذ الرقمي المتقن." },
  ],
  links: [{ rel: "canonical", href: "https://meswar.com/about" }],
  scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "AboutPage", name: "عن مسور المتطورة", url: "https://meswar.com/about", inLanguage: "ar", description: "شركة تقنية سعودية تبني حلولًا رقمية موثوقة تخدم الأعمال.", mainEntity: { "@id": "https://meswar.com/#organization" } }) }],
}), component: AboutPage });

function AboutPage() { return <SiteLayout><PageIntro eyebrow="عن مسور المتطورة" title="نصنع التقنية بقصد، ونبنيها لتدوم." description="شركة تقنية سعودية تجمع بين الفهم العميق للأعمال والتنفيذ الرقمي المتقن لتحويل التحديات إلى فرص نمو." />
<section className="section-block"><div className="site-container grid gap-10 lg:grid-cols-2"><div><span className="eyebrow">قصتنا</span><h2 className="section-title">من الفكرة إلى<br /><span>قيمة حقيقية.</span></h2></div><div className="space-y-5 text-base leading-8 text-muted-foreground"><p>في مسور المتطورة، نؤمن أن التقنية الناجحة تبدأ من فهم الإنسان والعمل. لذلك لا نبني منتجًا لمجرد البناء، بل نصمم حلًا يخدم هدفًا واضحًا ويصنع تجربة أفضل.</p><p>نعمل مع المنشآت ورواد الأعمال على تطوير المواقع والمنصات والأنظمة والحلول الذكية، بمنهج يجمع الوضوح والمرونة والجودة.</p></div></div></section>
<section className="section-block border-y border-border bg-surface-deep"><div className="site-container grid gap-5 md:grid-cols-3">{[{icon:Target,title:"رسالتنا",text:"تمكين الأعمال بحلول رقمية عملية ترفع الكفاءة وتفتح فرصًا جديدة للنمو."},{icon:Eye,title:"رؤيتنا",text:"أن نكون شريكًا تقنيًا موثوقًا في صناعة مستقبل رقمي أكثر ذكاءً ووضوحًا."},{icon:HeartHandshake,title:"قيمنا",text:"الوضوح، الإتقان، المسؤولية، وشراكة حقيقية تستمر بعد إطلاق المشروع."}].map(({icon:Icon,title,text})=><article className="value-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="section-block"><div className="site-container grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><span className="eyebrow">طريقة عملنا</span><h2 className="section-title">خطوات واضحة.<br /><span>نتائج مدروسة.</span></h2><div className="mt-8 grid gap-4">{["نفهم أهداف المشروع وتحدياته الحقيقية","نصمم التجربة والبنية التقنية المناسبة","نطور ونختبر بدقة قبل الإطلاق","نقيس ونحسن ونواصل الدعم"].map((item,i)=><div className="process-row" key={item}><span>0{i+1}</span><p>{item}</p><CheckCircle2/></div>)}</div></div><div className="quote-panel"><p>“هدفنا ليس تسليم مشروع تقني فقط، بل بناء أصل رقمي يساعد عملك على التقدم.”</p><span>فريق مسور المتطورة</span></div></div></section>
<section className="compact-cta"><div className="site-container flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><h2>ابدأ رحلتك الرقمية معنا</h2><p>شاركنا فكرتك، ودعنا نرسم طريق تنفيذها.</p></div><Button asChild size="lg" variant="premium"><Link to="/contact">تواصل معنا <ArrowLeft/></Link></Button></div></section></SiteLayout> }
