import { createFileRoute } from "@tanstack/react-router";
import { Building2, Clock3, MessageCircle, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, SiteLayout } from "@/components/site/site-shell";
export const Route = createFileRoute("/contact")({ head: () => ({
  meta: [
    { title: "تواصل مع مسور | ابدأ مشروعك الرقمي" }, { name: "description", content: "تواصل مع مسور المتطورة لمناقشة تطوير موقع أو منصة أو نظام أو حل ذكاء اصطناعي. اتصل أو أرسل تفاصيل مشروعك عبر واتساب." },
    { property: "og:title", content: "تواصل مع مسور المتطورة" }, { property: "og:description", content: "شاركنا فكرتك وابدأ بناء مشروعك الرقمي مع فريق مسور." }, { property: "og:type", content: "website" }, { property: "og:url", content: "https://meswar.com/contact" }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: "تواصل مع مسور المتطورة" }, { name: "twitter:description", content: "شاركنا احتياجك التقني وسنتواصل معك لفهم المشروع." },
  ],
  links: [{ rel: "canonical", href: "https://meswar.com/contact" }],
  scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "ContactPage", name: "تواصل مع مسور المتطورة", url: "https://meswar.com/contact", inLanguage: "ar", mainEntity: { "@id": "https://meswar.com/#organization" } }) }],
}), component: ContactPage });
function ContactPage(){return <SiteLayout><PageIntro eyebrow="تواصل معنا" title="لنتحدث عن فكرتك القادمة." description="أخبرنا بما تريد بناءه، وسنتواصل معك لفهم الاحتياج واقتراح الخطوة الأنسب." />
<section className="section-block"><div className="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><a href="tel:+966530044027" className="contact-card"><span><Phone/></span><div><small>اتصل بنا</small><strong dir="ltr">053 004 4027</strong></div></a><a href="https://wa.me/966530044027" target="_blank" rel="noreferrer" className="contact-card"><span><MessageCircle/></span><div><small>واتساب</small><strong>ابدأ المحادثة الآن</strong></div></a><div className="contact-card"><span><Building2/></span><div><small>الرقم الوطني الموحد</small><strong dir="ltr">7050514673</strong></div></div><div className="contact-card"><span><Clock3/></span><div><small>وقت الاستجابة</small><strong>خلال يوم عمل</strong></div></div></div>
<form className="contact-form" action="https://wa.me/966530044027" method="get" target="_blank"><div><label htmlFor="name">الاسم</label><input id="name" name="name" placeholder="اكتب اسمك" /></div><div><label htmlFor="phone">رقم التواصل</label><input id="phone" name="phone" inputMode="tel" placeholder="05x xxx xxxx" dir="ltr" /></div><div className="sm:col-span-2"><label htmlFor="service">نوع الخدمة</label><select id="service" name="service" defaultValue=""><option value="" disabled>اختر الخدمة المطلوبة</option><option>تطوير موقع</option><option>تطوير نظام أو منصة</option><option>حل ذكاء اصطناعي</option><option>تصميم تجربة مستخدم</option><option>خدمة أخرى</option></select></div><div className="sm:col-span-2"><label htmlFor="message">نبذة عن المشروع</label><textarea id="message" name="text" rows={5} placeholder="حدثنا عن فكرتك، الهدف منها، والنتيجة التي تطمح إليها..." /></div><div className="sm:col-span-2"><Button type="submit" size="lg" variant="premium" className="w-full">إرسال الطلب عبر واتساب <MessageCircle/></Button></div></form></div></section></SiteLayout>}
